### PR TITLE
Monero syncer: Add restore height for sweep wallet

### LINKED ISSUE #254: monero wallet rpc log previous upon successful sweeping
```
2021-11-29 03:04:09.237	E wrong number of additional derivations
2021-11-29 03:04:54.492	W Transaction extra has unsupported format: <eff6ab2c488124caf1ea02874a7a1606ed58df11eebf44e4c7818014f9472235>
... ^^ thousands of the line above with different values
2021-11-29 03:04:54.550	W Received money: 0.000100000000, with tx: <fe6fa11669b3b21afc981815954d5428739cfde4ab0a974c5689b65757be7964>
2021-11-29 03:04:55.240	W Loaded wallet keys file, with public address: 5BMsjsoFbVEKaN5jDwszevUrt5evxAtFSEQDGfNnnpcyFomiVpFVYfRJtbi9kUBBo95zgJiPfSHcm3pGurKbdUDEJMAUqJy
2021-11-29 03:04:56.334	W Loaded wallet keys file, with public address: 5BMsjsoFbVEKaN5jDwszevUrt5evxAtFSEQDGfNnnpcyFomiVpFVYfRJtbi9kUBBo95zgJiPfSHcm3pGurKbdUDEJMAUqJy
2021-11-29 03:04:56.759	W amount=0.000100000000, real_output=10, real_output_in_tx_index=1, indexes: 4346198 4364888 4365462 4372823 4372946 4373634 4374205 4374206 4374690 4374753 4374866 
2021-11-29 03:04:56.763	W amount=0.000100000000, real_output=10, real_output_in_tx_index=1, indexes: 4346198 4364888 4365462 4372823 4372946 4373634 4374205 4374206 4374690 4374753 4374866 
2021-11-29 03:04:56.767	W amount=0.000100000000, real_output=10, real_output_in_tx_index=1, indexes: 4346198 4364888 4365462 4372823 4372946 4373634 4374205 4374206 4374690 4374753 4374866 
2021-11-29 03:04:59.166	W Loaded wallet keys file, with public address: 5BMsjsoFbVEKaN5jDwszevUrt5evxAtFSEQDGfNnnpcyFomiVpFVYfRJtbi9kUBBo95zgJiPfSHcm3pGurKbdUDEJMAUqJy
```

### PR DESCRIPTION
**Pull request by TheCharlatan**
This is supposed to fix #254 , please test if this makes the excessive monero-wallet-rpc logging disappear.

### CODE REVIEW

File: src/swapd/runtime.rs [hunk 1]
```diff
@@ -711,15 +712,6 @@ impl SyncerState {
...
         });
-        let from_height = match self.lock_tx_confs {
-            Some(Request::SyncerEvent(Event::TransactionConfirmations(
-                TransactionConfirmations {
-                    confirmations: Some(tx_confs),
-                    ..
-                },
-            ))) => Some(self.monero_height - tx_confs as u64),
-            _ => None,
-        };
```
Comment (zkao) [inline src/swapd/runtime.rs]: lock_tx_confs contains the bitcoin lock confs, in btc blocks, not xmr blocks

**Comment by zkao** [comment]
> This is supposed to fix #254 , please test if this makes the excessive monero-wallet-rpc logging disappear.

I confirm the applied patch fixes the issue

**Review by zkao — APPROVED** [review]

File: src/swapd/runtime.rs (hunk 1 above)
Comment (TheCharlatan) [reply src/swapd/runtime.rs]: Damn, I still find the `lock` terminology confusing, but after reading it again, it's more clear to me now. Still, the confirmations (so the block height of the sent transaction) and not the current block height should be taken into account.

Comment (zkao) [reply src/swapd/runtime.rs]: i agree. that special lock_tx_confs was created ad-hoc to replay the last syncer event when receiving txs from wallet (and updating swapd state), so that if there is some action to trigger in swapd, it triggers right after having the tx available (it becomes reactive)

File: src/swapd/runtime.rs [hunk 2]
```diff
@@ -1498,9 +1500,13 @@ impl Runtime {
                             .expect("Checked above")
                             .pop()
                             .unwrap();
-                        if let (Request::SyncerTask(Task::SweepAddress(..)), ServiceBus::Ctl) =
-                            (&request, &bus_id)
+                        if let (Request::SyncerTask(Task::SweepAddress(mut task)), ServiceBus::Ctl) =
+                            (request.clone(), bus_id.clone())
                         {
+                            // safe cast
+                            task.from_height = Some(self.syncer_state.monero_height - *confirmations as u64);
```
Comment (zkao) [inline src/swapd/runtime.rs:1507]: this is happening twice, here and later on the syncer

File: src/syncerd/monero_syncer.rs [hunk 3]
```diff
@@ -224,12 +224,19 @@ async fn sweep_address(
...
     let password = s!(" ");
     let address = monero::Address::from_keypair(*network, &keypair);
     let wallet_filename = format!("sweep:{}", address);
 
+    // add some extra leeway for the wallet restore height
+    let restore_height = match from_height {
+        Some(height) if height > 10 => Some(height - 10),
+        _ => None,
+    };
+
```
Comment (zkao) [inline src/syncerd/monero_syncer.rs:239]: 2nd time: this gives too many degrees of freedom

**Review by zkao — APPROVED** [review]

File: src/syncerd/monero_syncer.rs (hunk 3 above)
Comment (TheCharlatan) [reply src/syncerd/monero_syncer.rs:239]: Let me test again without it and then drop it. Kind of weird to have this in the first place.

Comment (TheCharlatan) [reply src/syncerd/monero_syncer.rs]: Dropped in fa8a433443e39f15c753f598c8ae704b06a5d4d1
